import matter from "gray-matter";
import type { AgentsMdPayload } from "./schema.js";

// PR-F.2.2: serialize AGENTS.md payload back to YAML-front-matter markdown.
// Free-text body is a fixed header explaining the file's origin.
// gray-matter.stringify handles YAML emission with quoting + indentation.

const BODY = `# Prospero — Team manifest

This file was generated by Prospero. Edit the front-matter above to add
agents, change roles, or rewire reporting. Re-import via Settings → "Import
from AGENTS.md".
`;

export const serializeAgentsMd = (payload: AgentsMdPayload): string => {
  const data: Record<string, unknown> = { company: payload.company };
  if (payload.projects.length > 0) {
    data.projects = payload.projects;
  }
  data.agents = payload.agents.map((a) => {
    const out: Record<string, unknown> = { name: a.name, role: a.role };
    if (a.model !== undefined) out.model = a.model;
    if (a.capabilities !== undefined && a.capabilities.length > 0)
      out.capabilities = a.capabilities;
    if (a.reports_to !== undefined) out.reports_to = a.reports_to;
    if (a.projects !== undefined && a.projects.length > 0) out.projects = a.projects;
    return out;
  });
  return matter.stringify(BODY, data);
};
