import matter from "gray-matter";
import type { AgentsMdPayload } from "./schema.js";

// PR-F.2.2 / M12 PR-D4: serialize an AGENTS.md payload back to YAML-front-matter
// markdown. gray-matter.stringify (js-yaml) emits multi-line strings — like a
// role's charter — as readable block scalars, so the whole company stays in
// the structured, zod-validated front-matter.

const BODY = `# Prospero — Team manifest

This file was generated by Prospero. Edit the front-matter above to add roles,
agents, change charters, or rewire reporting. Re-import via
Settings → "Import from AGENTS.md".
`;

export const serializeAgentsMd = (payload: AgentsMdPayload): string => {
  const data: Record<string, unknown> = { company: payload.company };
  if (payload.projects.length > 0) {
    data.projects = payload.projects;
  }
  if (payload.roles !== undefined && payload.roles.length > 0) {
    data.roles = payload.roles.map((r) => {
      const out: Record<string, unknown> = { name: r.name };
      if (r.description !== undefined) out.description = r.description;
      if (r.model !== undefined) out.model = r.model;
      if (r.capabilities !== undefined && r.capabilities.length > 0)
        out.capabilities = r.capabilities;
      if (r.icon !== undefined) out.icon = r.icon;
      if (r.charter !== undefined) out.charter = r.charter;
      return out;
    });
  }
  data.agents = payload.agents.map((a) => {
    const out: Record<string, unknown> = { name: a.name, role: a.role };
    if (a.model !== undefined) out.model = a.model;
    if (a.capabilities !== undefined && a.capabilities.length > 0)
      out.capabilities = a.capabilities;
    if (a.reports_to !== undefined) out.reports_to = a.reports_to;
    if (a.projects !== undefined && a.projects.length > 0) out.projects = a.projects;
    return out;
  });
  return matter.stringify(BODY, data);
};
