import { ipcMain } from "electron";
import type Database from "better-sqlite3";
import { IPC } from "@prospero/shared";
import { registerSettingsHandlers } from "./settings-handlers.js";
import { registerAuthHandlers } from "./auth-handlers.js";
import { registerCompaniesHandlers } from "./companies-handlers.js";
import { registerMessagesHandlers } from "./messages-handlers.js";
import { registerOrchestratorHandlers } from "./orchestrator-handlers.js";
import { registerPermissionHandlers } from "./permission-handlers.js";
import { registerInboxHandlers } from "./inbox-handlers.js";
import { registerProjectsHandlers } from "./projects-handlers.js";
import { registerIssuesHandlers } from "./issues-handlers.js";
import { registerRolesHandlers } from "./roles-handlers.js";
import { registerActivityHandlers } from "./activity-handlers.js";
import { registerCostsHandlers } from "./costs-handlers.js";
import { registerRunsHandlers } from "./runs-handlers.js";
import { registerAgentsMdHandlers } from "./agents-md-handlers.js";
import { registerLearningHandlers } from "./learning-handlers.js";
import { registerInstructionsHandlers } from "./instructions-handlers.js";
import { registerOrgPlanHandlers } from "./org-plan-handlers.js";
import { registerIsaHandlers } from "./isa-handlers.js";
import { initRecorder } from "../activity/index.js";
import { initDerivation } from "../derivation/index.js";
import { recoverStuckVerifications } from "../verification/index.js";
import { buildVerificationDeps } from "../verification/deps.js";

export const registerIpcHandlers = (db: Database.Database): void => {
  ipcMain.handle(IPC.PING, () => "pong");
  const derivation = initDerivation(db);
  initRecorder(db, derivation.onActivity);
  // Fire-and-forget: at most a handful of goals can be stuck `verifying` at
  // restart (single-user scale) — no throttle needed.
  recoverStuckVerifications(db, buildVerificationDeps());
  registerSettingsHandlers(db);
  registerAuthHandlers(db);
  registerCompaniesHandlers(db);
  registerMessagesHandlers(db);
  registerOrchestratorHandlers(db);
  registerPermissionHandlers(db);
  registerInboxHandlers(db);
  registerProjectsHandlers(db);
  registerIssuesHandlers(db);
  registerRolesHandlers(db);
  registerActivityHandlers(db);
  registerCostsHandlers(db);
  registerRunsHandlers(db);
  registerAgentsMdHandlers(db);
  registerLearningHandlers(db);
  registerInstructionsHandlers(db);
  registerOrgPlanHandlers(db);
  registerIsaHandlers(db);
};
