export const IPC = {
  PING: "ping",
  SETTINGS_GET: "settings:get",
  SETTINGS_PICK_WORKSPACE: "settings:pick-workspace",
  SETTINGS_UPDATE: "settings:update",
  AUTH_TOKEN_STATUS: "auth:token-status",
  AUTH_TOKEN_SET: "auth:token-set",
  AUTH_TOKEN_DETECT: "auth:token-detect",
  AUTH_TOKEN_IMPORT_DETECTED: "auth:token-import-detected",
  AUTH_TOKEN_CLEAR: "auth:token-clear",
  COMPANY_LIST: "company:list",
  COMPANY_CREATE_DEMO: "company:create-demo",
  AGENT_LIST: "agent:list",
  AGENT_SEND_MESSAGE: "agent:send-message",
  AGENT_KILL: "agent:kill",
  AGENT_EVENT: "agent:event",
  MESSAGE_LIST: "message:list",
  MESSAGE_LIST_BY_AGENT: "message:list-by-agent",
  INBOX_LIST: "inbox:list",
  INBOX_MARK_READ: "inbox:mark-read",
  INBOX_UPDATE: "inbox:update",
  PERMISSION_REQUEST: "permission:request",
  PERMISSION_RESOLVE: "permission:resolve",
  PROJECTS_LIST: "projects:list",
  PROJECTS_CREATE: "projects:create",
  PROJECTS_UPDATE: "projects:update",
  PROJECTS_DELETE: "projects:delete",
  PROJECTS_OPEN_FOLDER: "projects:open-folder",
  PROJECTS_CHECK_PATHS: "projects:check-paths",
  AGENTS_SET_ALLOWED_PROJECTS: "agents:set-allowed-projects",
  ISSUES_LIST: "issues:list",
  ISSUES_GET: "issues:get",
  ISSUES_CREATE: "issues:create",
  ISSUES_UPDATE: "issues:update",
  ISSUES_DELETE: "issues:delete",
  ISSUES_ADD_COMMENT: "issues:add-comment",
  ISSUES_CHANGED: "issues:changed",
  ROLES_LIST: "roles:list",
  ROLES_GET: "roles:get",
  AGENTS_SET_MODEL: "agents:set-model",
  AGENTS_SET_ROLE: "agents:set-role",
  AGENTS_SET_SYSTEM_PROMPT: "agents:set-system-prompt",
  AGENTS_SET_REPORTS_TO: "agents:set-reports-to",
  AGENTS_STATS: "agents:stats",
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
